# Generated by Django 5.1.3 on 2025-01-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_information',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
