# Generated by Django 5.1.3 on 2025-01-28 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='video',
        ),
        migrations.AddField(
            model_name='comments',
            name='video',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user.management'),
        ),
    ]
