# Generated by Django 5.1.1 on 2024-11-16 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='likes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.management'),
        ),
    ]
