# Generated by Django 5.1.3 on 2025-01-28 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_comments_video_comments_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 28, 1, 43, 56, 560490, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
