# Generated by Django 5.1.1 on 2024-11-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_likes_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='likes',
            new_name='video',
        ),
    ]
