# Generated by Django 5.1.1 on 2024-11-16 23:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_likess'),
    ]

    operations = [
        migrations.AddField(
            model_name='likess',
            name='like_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
